kind: Secret
apiVersion: v1
metadata:
  name: postgresql
      operation: Update
      apiVersion: v1
      time: '2023-11-11T17:35:33Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:database-name': {}
          'f:database-password': {}
          'f:database-user': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:template.openshift.io/expose-database_name': {}
            'f:template.openshift.io/expose-password': {}
            'f:template.openshift.io/expose-username': {}
          'f:labels':
            .: {}
            'f:template': {}
            'f:template.openshift.io/template-instance-owner': {}
        'f:type': {}
data:
  database-name: c2FtcGxlZGI=
  database-password: NGhxbk5oRFc2MGpnQjRIQg==
  database-user: dXNlcldVTw==
type: Opaque
