kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: battalion-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem