apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pattalion-trigger-template
spec:
  params:
    - description: battalion
      name: battalion
    - name: battalion_id
      description: battalion id      
    - description: action
      name: action                  
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: battalion-pipeline-$(tt.params.battalion)-
      spec:
        params:
          - name: battalion
            value: $(tt.params.battalion)
          - name: battalion_id
            value: $(tt.params.battalion_id) 
          - name: action
            value: $(tt.params.action)                                     
        pipelineRef:
          name: battalion-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 128Mi
                storageClassName: ocs-external-storagecluster-ceph-rbd
                volumeMode: Filesystem