apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pattalion-trigger-template
spec:
  params:
    - description: battalion
      name: battalion
    - description: battalion id
      name: battalion_id      
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: battalion-pipeline-$(tt.params.battalion)-
      spec:
        params:
          - name: battalion
            value: $(tt.params.battalion)
          - name: battalion_id
            value: $(tt.params.battalion_id)             
        pipelineRef:
          name: battalion-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: source
            persistentVolumeClaim:
              claimName: battalion-pvc