apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2023-11-02T21:13:06Z'
  generation: 13
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2023-11-03T02:04:31Z'
  name: battalion-pipeline
  namespace: command-post
  resourceVersion: '535922'
  uid: d889670a-5a3f-4881-845c-399043ac7233
spec:
  params:
    - default: blue
      description: battalion name
      name: battalion
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/wael2000/mission-command'
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:9b14f52b21d29d8d83ea4c0e78623debc954f1a732d2be6d1a7269fbba23b1a4
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: openshift-client
      params:
        - name: SCRIPT
          value: 'oc new-project battalion-$(params.battalion) '
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: openshift-client-kzp
      params:
        - name: SCRIPT
          value: >-
            oc label ns battalion-$(params.battalion)
            argocd.argoproj.io/managed-by=demo-cicd 
        - name: VERSION
          value: latest
      runAfter:
        - openshift-client
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: source
    - name: openshift-client-yu3
      params:
        - name: SCRIPT
          value: >-
            sed 's/BATTALION/$(params.battalion)/g'
            battalion-apps/battalion-team-app.yaml | oc create -f - -n
            demo-cicd 
        - name: VERSION
          value: latest
      runAfter:
        - openshift-client-kzp
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: source
  workspaces:
    - name: source
