apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaces-manager
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-from-example-nonprod
  namespace: devops-test-nonprod
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: command-post
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespaces-manager