apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: bubble-event-listener
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: bubble-trigger-binding
      name: bubble-trigger
      template:
        ref: bubble-trigger-template