apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: battalion-notification-task
spec:
  description: Send status to Battalion backend
  params:
    - name: battalion
      type: string
      default: fox
    - name: battalion_url
      type: string
  workspaces:
    - name: workspace
  steps:
    - name: configure
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |
        #!/usr/bin/env bash

        curl -XPOST -d '{"battalion","$(params.battalion)"}' $(params.battalion_url)