apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: battalion-task
spec:
  description: Configure Battalion Team
  params:
    - name: battalion
      type: string
      default: fox
  workspaces:
    - name: workspace
  steps:
    - name: configure
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |
        #!/usr/bin/env bash

        
        sed -i 's/TARGET_NAMESPACE/$(params.battalion)/g' apps/battalion-team-app.yaml

        cat "apps/battalion-team-app.yaml"