---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: battalion
  name: $(params.battalion)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $(params.battalion)
  strategy: {}
  template:
    metadata:
      labels:
        app: $(params.battalion)
    spec:
      containers:
      - image: quay.io/rhdevelopers/bgd:1.0.0
        name: $(params.battalion)
        env:
        - name: COLOR
          value: "blue"
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
