apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
spec:
  destination:
    namespace: command-post
    server: https://kubernetes.default.svc
  project: default
  source:
    path: adds/bgd
    repoURL: https://github.com/wael2000/mission-command
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: false