apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgdk-app
spec:
  destination:
    namespace: user$USERNUM-bgdk
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/bgdk
    repoURL: https://github.com/wael2000/mission-command
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: false