apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-battalion
spec:
  params:
    - default: blue
      description: battalion name
      name: battalion
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/wael2000/mission-command'
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:9b14f52b21d29d8d83ea4c0e78623debc954f1a732d2be6d1a7269fbba23b1a4
        - name: userHome
          value: /home/git
        - name: revision
          value: ''
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: openshift-client
      params:
        - name: SCRIPT
          value: >-
            oc new-project battalion-$(params.battalion) | oc label ns
            battalion-$(params.battalion)
            argocd.argoproj.io/managed-by=demo-cicd | oc apply -f
            apps/battalion-team-app.yaml -n demo-cicd
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: source
  workspaces:
    - name: source
